services:
  node-server:
    build: ./node-server
    restart: on-failure
    env_file:
      - .env
    hostname: "${NODE_SERVER_HOSTNAME}"
  holidays-server:
    build: ./holidays-server
    volumes:
      - ./holidays-server/db:/usr/share/nginx/html
    hostname: "${HOLIDAYS_SERVER_HOSTNAME}"
  proxy-server:
    build: ./proxy-server
    ports:
      - "80:80"
    depends_on:
      - node-server
      - holidays-server
